### PR TITLE
feature:enabled search filter

### PR DESCRIPTION
**Pull request by GbCderr14**
## Issue <> 🎯🎯
Enabled Search by Query filter addressed by issue #73 

## Description
Now the search input field will filter the courses by input text and will display a list of filtered courses just below the search bar and when user will click on that course from the list that course details page will get opened and if user will just clicks on the search button adjacent to the input field then now the filtered course cards will be visible to the user only.

## Screenshots 📷
image

If search button got clicked
image

### CODE REVIEW

**Comment by CodeTorso** [comment]
Give me 5-10 minutes. Looking into changes

**Comment by GbCderr14** [comment]
Ok sure

**Comment by CodeTorso** [comment]
A react PR is on it's way to getting merged. (pending from 1 week)

You will get notifications regarding this PR by tomorrow 8 am.

We hope you understand.

**Comment by GbCderr14** [comment]
Ok ok no problem By the way Is it fine? Or i need to improve something in this?

**Comment by CodeTorso** [comment]
I will check it by tomorrow morning. 

Another person also made the PR on same topic

It took him 112 lines if your code works. Good for you then.

**Comment by GbCderr14** [comment]
Okay

**Comment by GbCderr14** [comment]
Can you add hacktoberfest ,hacktoberfest-accepted 
label to it

**Pull request merged**
