### PR TITLE
Added responsive navbar successfully.

### PR DESCRIPTION
**Pull request by Haris-Mohanty**
## Description

This pull request aims to enhance the project's navigation bar to be responsive, ensuring a seamless user experience on various devices and screen sizes. The changes made include the following:

## Testing:

-  Tested on various screen sizes and devices to ensure responsiveness.
-  Verified that all existing navbar functionality remains intact.

## Screenshots 📷
   BEFORE:
   
Screenshot 2023-10-01 092916

AFTER :
Screenshot 2023-10-01 093137

Thank you for considering this contribution. I'm open to feedback and ready to make any necessary adjustments to ensure the successful integration of this enhancement into the project.

### CODE REVIEW

**Comment by Haris-Mohanty** [comment]
Code just formatted, that's why showing so  many changes. I was just add changes at media screen.

**Comment by vedantmistryy** [comment]
solve the conflicts @Haris-Mohanty

**Comment by Haris-Mohanty** [comment]
@vedantmistryy, what's confilts... sorry to say that I don't understand. The Navbar is not responsive yet.

**Comment by CodeTorso** [comment]
hello @Haris-Mohanty,

1) press ctrl + F 

2) Type 'resolve conflicts'

You see there is this button showing resolve conflict that means your PR has some conflicts. 

We will get to you by 8 am tomorrow

**Comment by CodeTorso** [comment]
Wait give me time seems as if conflicts are resolved by my code. Let me see your code

**Comment by CodeTorso** [comment]
I checked your code locally. It has some style linking errors. please fix it with the new PR.

Start working only by tomorrow's website code.

**Comment by Haris-Mohanty** [comment]
@CodeTorso , Ok bro.

**Pull request closed without merging**
